# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(890, 684)
        Form.setStyleSheet("QPushButton{\n"
"    background:\"black\";\n"
"    color:\"white\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:\"#33a2ff\";\n"
"}")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(20, 20, 851, 131))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(40, 20, 71, 16))
        self.label.setObjectName("label")
        self.label_first_name = QtWidgets.QLineEdit(parent=self.widget)
        self.label_first_name.setGeometry(QtCore.QRect(110, 20, 201, 21))
        self.label_first_name.setObjectName("label_first_name")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_last_name = QtWidgets.QLineEdit(parent=self.widget)
        self.label_last_name.setGeometry(QtCore.QRect(110, 70, 201, 21))
        self.label_last_name.setObjectName("label_last_name")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(400, 20, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_age = QtWidgets.QLineEdit(parent=self.widget)
        self.label_age.setGeometry(QtCore.QRect(440, 20, 201, 21))
        self.label_age.setObjectName("label_age")
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setGeometry(QtCore.QRect(400, 70, 71, 16))
        self.label_4.setObjectName("label_4")
        self.labe_email = QtWidgets.QLineEdit(parent=self.widget)
        self.labe_email.setGeometry(QtCore.QRect(440, 70, 201, 21))
        self.labe_email.setObjectName("labe_email")
        self.widget_2 = QtWidgets.QWidget(parent=Form)
        self.widget_2.setGeometry(QtCore.QRect(20, 160, 851, 131))
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 851, 121))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_btn = QtWidgets.QPushButton(parent=self.widget_3)
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout.addWidget(self.search_btn)
        self.create_btn = QtWidgets.QPushButton(parent=self.widget_3)
        self.create_btn.setObjectName("create_btn")
        self.horizontalLayout.addWidget(self.create_btn)
        self.update_btn = QtWidgets.QPushButton(parent=self.widget_3)
        self.update_btn.setObjectName("update_btn")
        self.horizontalLayout.addWidget(self.update_btn)
        self.delete_btn = QtWidgets.QPushButton(parent=self.widget_3)
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout.addWidget(self.delete_btn)
        self.clear_btn = QtWidgets.QPushButton(parent=self.widget_3)
        self.clear_btn.setObjectName("clear_btn")
        self.horizontalLayout.addWidget(self.clear_btn)
        self.widget_4 = QtWidgets.QWidget(parent=Form)
        self.widget_4.setGeometry(QtCore.QRect(20, 300, 851, 361))
        self.widget_4.setObjectName("widget_4")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.widget_4)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 831, 341))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "first_name"))
        self.label_2.setText(_translate("Form", "last_name"))
        self.label_3.setText(_translate("Form", "age"))
        self.label_4.setText(_translate("Form", "email"))
        self.search_btn.setText(_translate("Form", "SEARCH"))
        self.create_btn.setText(_translate("Form", "CREATE"))
        self.update_btn.setText(_translate("Form", "UPDATE"))
        self.delete_btn.setText(_translate("Form", "DELETE"))
        self.clear_btn.setText(_translate("Form", "CLEAR"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "first_name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "last_name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "age"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "email"))
